import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "Content Creation Institute",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="md:w-[98%] mx-auto mt-1">{children}</body>
    </html>
  );
}
