import Head from "next/head";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

import { Hind_Siliguri } from "next/font/google";

const hindSiliguri = Hind_Siliguri({
  subsets: ["bengali"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Content Creation Institute",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={`md:w-[98%] mx-auto mt-1 ${hindSiliguri.className} `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
