import Head from "next/head";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Content Creation Institute",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html>
      <Navbar />
      <body className="md:w-[98%] mx-auto mt-1">{children}</body>
      <Footer />
    </html>
  );
}
